# Generated by Django 5.1.4 on 2024-12-21 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget', models.BigIntegerField(default=0)),
                ('homepage', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('original_language', models.TextField(blank=True, default='', null=True)),
                ('overview', models.TextField(blank=True, default='', null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(default=0)),
                ('runtime', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('In Production', 'In Production'), ('Post-Production', 'Post-Production'), ('Cancelled', 'Cancelled'), ('NA', 'NA')], default='Released', max_length=20)),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.genre')),
                ('languages', models.ManyToManyField(blank=True, null=True, to='movie.language')),
                ('production_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.production')),
            ],
        ),
    ]
